package com.finanzen.api.infrastructure.exception;

import java.util.List;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;


import jakarta.persistence.EntityNotFoundException;

@RestControllerAdvice
public class GlobalExceptionHandler {
    /**
     * Data Transfer Object used to encapsulate field validation errors.
     * Translates the complex Spring FieldError object into a simple key-value pair (field name and message).
     */
    public record FieldErroDto(String field, String message) {
        public FieldErroDto(FieldError error){
            this(error.getField(), error.getDefaultMessage());
        }
    }
    
    /**
     * Handles exceptions thrown when a requested entity is not found in the database.
     * <p>
     * This method intercepts {@link EntityNotFoundException} across the entire application
     * and translates it into a standard HTTP 404 (Not Found) response. This prevents internal
     * server errors and stack traces from leaking to the client, providing a clear and precise
     * indication that the requested resource does not exist.
     * </p>
     *
     * @param e the exception indicating the entity was not found.
     * @return a {@link ResponseEntity} with status 404 (Not Found) and an empty body.
     */
    @ExceptionHandler(EntityNotFoundException.class)
    public ResponseEntity<Void> handleEntityNotFound(EntityNotFoundException e){
        return ResponseEntity.notFound().build();
    }


    /**
     * Handles validation exceptions thrown when method arguments annotated with @Valid fail validation.
     * <p>
     * This method intercepts {@link MethodArgumentNotValidException}, extracts the raw field errors
     * generated by Spring, and maps them into a clean list of {@link FieldErrorDto}. This ensures
     * the API client receives a structured and readable 400 Bad Request response, detailing exactly
     * which fields failed and why.
     * </p>
     *
     * @param e the exception containing the validation errors.
     * @return a {@link ResponseEntity} with status 400 (Bad Request) and the list of formatted errors in the body.
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<List<FieldErroDto>> handleBadRequest(MethodArgumentNotValidException e){
        var errors = e.getFieldErrors();

        List<FieldErroDto> listErrors = errors.stream().map(error -> new FieldErroDto(error)).toList();

        return ResponseEntity.badRequest().body(listErrors);

    }

}
